import { useRef, useState } from "react";

import { COUNTRIES } from "../config/countries";


export default function ProfileExportCard({ profile, countryCode }) {
  const exportRef = useRef(null);
  const [downloading, setDownloading] = useState(false);
  const country = COUNTRIES.find((entry) => entry.code === countryCode);

  async function downloadCard() {
    if (!exportRef.current || !window.html2canvas) {
      return;
    }

    setDownloading(true);
    try {
      const canvas = await window.html2canvas(exportRef.current, {
        backgroundColor: "#141917",
        scale: 2,
      });
      const url = canvas.toDataURL("image/png");
      const link = document.createElement("a");
      link.href = url;
      link.download = "unmapped-profile-card.png";
      link.click();
    } finally {
      setDownloading(false);
    }
  }

  return (
    <section className="section-card export-section">
      <div className="section-copy-block">
        <p className="eyebrow">PROFILE EXPORT</p>
        <h3>Download Profile Card</h3>
        <p className="section-copy">
          Save a clean snapshot of the mapped profile to share with employers, facilitators, or training programs.
        </p>
      </div>

      <div className="export-layout">
        <div className="profile-export-card" ref={exportRef}>
          <div className="profile-export-head">
            <div>
              <p className="export-kicker">Your Profile</p>
              <h4>{profile.isco_unit_label}</h4>
            </div>
            <div className="export-qr">Shareable link</div>
          </div>

          <div className="export-stat-row">
            <div className="key-stat">
              <span className="stat-label">ISCO</span>
              <strong className="stat-number">{profile.isco_unit_code}</strong>
            </div>
            <div className="key-stat">
              <span className="stat-label">Portability</span>
              <strong className="stat-number">{profile.portability_score}</strong>
            </div>
          </div>

          <div className="badge-list">
            {profile.esco_skills.slice(0, 4).map((skill) => (
              <span className="tag-pill static" key={skill}>
                {skill}
              </span>
            ))}
          </div>

          <div className="export-footer">
            <span className="export-country">
              {country?.flag} {country?.name}
            </span>
            <span className="export-meta">Generated by UNMAPPED · unmapped.vercel.app</span>
          </div>
        </div>

        <button className="button" type="button" onClick={downloadCard} disabled={downloading}>
          {downloading ? "Preparing Card..." : "Download Profile Card"}
        </button>
      </div>
    </section>
  );
}
